# Generated by Django 5.2.4 on 2025-07-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("join_date", models.DateTimeField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=255, unique=True)),
                ("user_id", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_details",
            },
        ),
        migrations.CreateModel(
            name="JWTToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("token", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "jwt_tokens",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="jwt_tokens_user_id_cb9a8b_idx"
                    ),
                    models.Index(fields=["token"], name="jwt_tokens_token_3d6d4f_idx"),
                    models.Index(
                        fields=["is_active"], name="jwt_tokens_is_acti_fa17d5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.user",
                    ),
                ),
            ],
            options={
                "db_table": "leaderboard",
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("game_mode", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.user",
                    ),
                ),
            ],
            options={
                "db_table": "gamesession",
                "indexes": [
                    models.Index(fields=["user"], name="gamesession_user_id_de2767_idx")
                ],
            },
        ),
    ]
